name: thibaitizokutansaku_map
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.3
  freezed_annotation: ^2.4.4
  flutter_map: ^7.0.2
  flutter_map_animations: ^0.7.1
  shared_preferences: ^2.3.2
  awesome_dialog: ^3.2.1
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:
  assets:
    - assets/images/asahi.jpg
    - assets/images/hagoromonomatu.jpg
    - assets/images/honkyouzi.jpg
    - assets/images/honmati.jpg
    - assets/images/inohana.jpg
    - assets/images/inzyuuzi.jpg
    - assets/images/katorizinzya.jpg
    - assets/images/kimimatibasi.jpg
    - assets/images/kimimatibasinohi.jpg
    - assets/images/koutokuzi.jpg
    - assets/images/otyanomizu.jpg
    - assets/images/tibazinzya.jpg
    - assets/images/tikouinn.jpg
    - assets/images/toorimati2.jpg
    - assets/images/5.jpg
    - assets/images/10.png
    - assets/images/14.png
    - assets/images/startimage.jpg
    - assets/images/tunetane.png
    - assets/images/chiba.jpg

  uses-material-design: true

